# -*- coding: utf-8 -*-
"""titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb3lHYxoAIx2Q15xawW7jtfLjT-F2U0K
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import files
uploaded = files.upload()

import pandas as pd

train_df = pd.read_csv("train.csv")
print(train_df)

print("count of null values:", train_df.isnull().sum())



#IMPUTATION!!!
from sklearn.impute import SimpleImputer
import numpy as np
train_df['Age'] = train_df['Age'].fillna(train_df['Age'].mean())
train_df['Embarked'] = train_df['Embarked'].fillna('S')
train_df['Cabin'] = train_df['Cabin'].fillna('Unknown')
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
train_df[train_df.select_dtypes(include=[np.number]).columns] = imputer.fit_transform(train_df.select_dtypes(include=[np.number]))


print("After Imputation!!!!!", train_df)


train_df = train_df.drop(columns = ['Cabin'])
train_df = train_df.drop(columns = ['Name'])
train_df = train_df.drop(columns = ['Ticket'])
train_df.columns

train_df['Sex'] = train_df['Sex'].map({'male' : 0, 'female' : 1})
print(train_df)                                                                           # "after removing the Cabin,Name,Ticket column beacause of a lot of missing values!!!"
train_df = pd.get_dummies(train_df, columns =['Embarked'])
print("encoded", train_df)

#SCALING!!!!!
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(train_df)





print("statistics:", train_df.describe())
print("information:",train_df.info())

import matplotlib
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
# %matplotlib inline


sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] == 19
matplotlib.rcParams['figure.figsize']== (10,8)



# TO VISUALIZE THE DISTRIBUTION OF SURVIVED PEOPLE:
fig1 = px.histogram(train_df,
                    x = 'Survived',
                    nbins = 2,
                    marginal='box',
                    title ='DISTRIBUTION OF SURVIVED PEOPLE',
                    )
fig1.update_layout(width=900,
                  height=500,
                  bargap=0.2)
fig1.show()




# TO VISUALIZE THE DISTRIBUTION OF Pclass:
fig2 = px.histogram(train_df,
                    x = 'Pclass',
                    nbins = 3,
                    marginal='box',
                    title ='DISTRIBUTION OF Pclass',
                    )
fig2.update_layout(width=900,
                  height=500,
                  bargap=0.2)
fig2.show()


#TO VISUALIZE THE DISTRIBUTION OF PCLASS VS SURVIVED:
fig3 = px.histogram(train_df,
                    x = 'Pclass',
                    y = 'Survived',
                    nbins = 3,
                    marginal='box',
                    title ='DISTRIBUTION OF Pclass VS SURVIVED',
                    )
fig3.update_layout(width=900,
                  height=500,
                  bargap=0.2)
fig3.show()

#TO VISUALIZE THE DISTRIBUTION OF EMBARKED VS SURVIVED:
fig4 = px.histogram(train_df,
                    x = 'Embarked_S',
                    y = 'Survived',
                    nbins = 3,
                    marginal='box',
                    title ='DISTRIBUTION OF Pclass VS SURVIVED',
                    )
fig4.update_layout(width=900,
                  height=500,
                  bargap=0.2)
fig4.show()





print(train_df.corr())                                                                     #"correlation between different features!!!!"

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier



# x = train_df[['Pclass','Fare']]
x = train_df[['Pclass', 'Sex', 'Age', 'Fare', 'SibSp', 'Parch', 'Embarked_C', 'Embarked_Q', 'Embarked_S']]
y = train_df['Survived']



x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

model = LogisticRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
print("accuracy : ",accuracy_score(y_test , y_pred))


#DECISION TREE ALGORITHM!!!
dt_model = DecisionTreeClassifier(random_state=42,max_depth=10,min_samples_split=15,min_samples_leaf=7)
dt_model.fit(x_train, y_train)

y_dt_pred = dt_model.predict(x_test)
print("decision tree algorithm's accuracy : ", accuracy_score(y_test,y_dt_pred))

#RANDOM FOREST CLASSIFIER!!!
rf_model = RandomForestClassifier(n_estimators = 10,max_depth=10,min_samples_split=7,min_samples_leaf=7)
rf_model.fit(x_train,y_train)

y_rf_pred = rf_model.predict(x_test)
print("random forest algorithm's accuracy : ", accuracy_score(y_test, y_rf_pred))


#GRADIENT BOOSTING ALGORITHM!!!
gb_model = GradientBoostingClassifier(n_estimators = 10, max_depth=10,min_samples_split=7,min_samples_leaf=7)
gb_model.fit(x_train,y_train)

y_gb_pred = gb_model.predict(x_test)
print("gradient boosting algorithm's accuracy : ", accuracy_score(y_test, y_gb_pred))

